#!/bin/bash
# live-hook script
# script name: hookscript

# squeeze live-boot (findiso only works with grml patch)
#if [ -d /live/findiso ]; then
#LIVEMEDIAMOUNTPOINT="/live/findiso"
#else
#LIVEMEDIAMOUNTPOINT="/live/image"
#fi

# sid live-boot
if [ -d /lib/live/findiso ]; then
LIVEMEDIAMOUNTPOINT="/lib/live/findiso"
else
LIVEMEDIAMOUNTPOINT="/lib/live/mount/medium"
fi

echo ""
echo " Running live hook scripts "
echo ""
sleep 2
cp -a $LIVEMEDIAMOUNTPOINT/live/hooks/lukshome /etc/init.d/
update-rc.d lukshome defaults
