#!/bin/sh
# elaborado por sinfallas
# cambia los permisos de los directorios de tor
set -e
rm -rf /var/log/tor /var/lib/tor
mkdir -p /var/log/tor
mkdir -p /var/lib/tor
chown debian-tor:debian-tor /var/log/tor /var/lib/tor
chmod 600 /var/lib/tor /var/log/tor
chmod u+x /var/lib/tor /var/log/tor
chgrp debian-tor /etc/tor/ /etc/tor/*
chmod g+rw /etc/tor/ /etc/tor/*
exit 0
